/**
 * BookingInputIntegrationLocation20240813IntegrationEnum
 */
export type BookingInputIntegrationLocation20240813IntegrationEnum =
  | "around-video"
  | "cal-video"
  | "campfire-video"
  | "demodesk-video"
  | "discord-video"
  | "eightxeight-video"
  | "element-call-video"
  | "facetime-video"
  | "google-meet"
  | "huddle"
  | "jelly-conferencing"
  | "jelly-video"
  | "jitsi"
  | "mirotalk-video"
  | "office365-video"
  | "ping-video"
  | "riverside-video"
  | "roam-video"
  | "salesroom-video"
  | "shimmer-video"
  | "signal-video"
  | "sirius-video"
  | "skype-video"
  | "sylaps-video"
  | "tandem"
  | "telegram-video"
  | "webex-video"
  | "whatsapp-video"
  | "whereby-video"
  | "zoom";
