/**
 * CreateWebhookInputDtoTriggersEnum
 */
export type CreateWebhookInputDtoTriggersEnum =
  | "AFTER_GUESTS_CAL_VIDEO_NO_SHOW"
  | "AFTER_HOSTS_CAL_VIDEO_NO_SHOW"
  | "BOOKING_CANCELLED"
  | "BOOKING_CREATED"
  | "BOOKING_NO_SHOW_UPDATED"
  | "BOOKING_PAID"
  | "BOOKING_PAYMENT_INITIATED"
  | "BOOKING_REJECTED"
  | "BOOKING_REQUESTED"
  | "BOOKING_RESCHEDULED"
  | "FORM_SUBMITTED"
  | "FORM_SUBMITTED_NO_EVENT"
  | "INSTANT_MEETING"
  | "MEETING_ENDED"
  | "MEETING_STARTED"
  | "OOO_CREATED"
  | "RECORDING_READY"
  | "RECORDING_TRANSCRIPTION_GENERATED";
